import Footer from "@/components/Footer";
import "./globals.css";
import { Poppins } from "next/font/google";
import { Search } from "@/components/Search";

const poppins = Poppins({
  subsets: ["latin"],
  weight: ["100", "200", "300", "400", "500", "600", "700", "800", "900"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={poppins.className}>
        <main className="flex flex-col items-center justify-center align-middle">
          <Search />
          <div className="px-4 py-2">{children}</div>
        </main>
        <Footer />
      </body>
    </html>
  );
}
